# Generated by Django 5.0.6 on 2024-07-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_urls',
            field=models.JSONField(default=dict),
        ),
    ]
