# Generated by Django 5.0.6 on 2024-07-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_activeuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
