# Generated by Django 5.0.6 on 2024-07-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_activeuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_urls',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
