# Generated by Django 5.0.6 on 2024-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0008_devices_remove_user_device_urls_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='MiniApp_Images')),
            ],
        ),
    ]
