# Generated by Django 5.0.6 on 2024-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Familiar', max_length=255),
        ),
    ]
